version: '3'
services:
  qwikclient:
    image: ghcr.io/valdtechsso/dnetqwikcmp:main
    networks:
      datalnet:
       ipv4_address: 192.168.0.14
    ports:
      - "3000:3000"
networks:
  datalnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
