FROM node:19.5.0-alpine3.16

# set working directory
WORKDIR /app

# install app dependencies
COPY package*.json ./

RUN npm install

# add app
COPY . .

RUN npm run build

# start app
CMD ["npm", "run", "deploy"]